sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install -U tox-travis pip setuptools setuptools_scm wheel
    - python3 ./setup.py bdist_wheel
    - pip install ./dist/*.whl
script: tox
